### ISSUE TITLE
Displayed as selected, but immediately restarted, looping continuously

### ISSUE THREAD

**Issue by today2004** [TheFalloutOf76/CDP-bug-MouseEvent-.screenX-.screenY-patcher#2]
Running DrissionPage_example.py on Linux, it was found through page.screencast that the click was indeed selected, but it immediately restarted and kept looping。

**Comment by ObjectAscended** [comment]
cant see the video, try uploading it somewhere else

also are you using headless?

**Comment by today2004** [comment]
co.set_flag('headless', 'new') or default 
come to the same thing
videourl：https://www.123pan.com/s/vjj8Vv-F0IUh.html

**Comment by ObjectAscended** [comment]
```py
co.headless()

from sys import platform
if platform == "linux" or platform == "linux2":
    platformIdentifier = "X11; Linux x86_64"
elif platform == "darwin":
    platformIdentifier = "Macintosh; Intel Mac OS X 10_15_7"
elif platform == "win32":
    platformIdentifier = "Windows NT 10.0; Win64; x64"

co.set_user_agent(f"Mozilla/5.0 ({platformIdentifier}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36")
```

check out the latest commit

**Comment by ObjectAscended** [comment]
tell me if it works

**Comment by today2004** [comment]
> tell me if it works

The problem persists。

**Comment by ObjectAscended** [comment]
> > tell me if it works
> 
> The problem persists。

you should use these tools to compare the different browser fingerprints:

headers: [echo.free.beeceptor.com](https://echo.free.beeceptor.com/)
tls: [tls.peet.ws/api/tls](https://tls.peet.ws/api/tls)

tell me what you see

**Comment by today2004** [comment]
> > > tell me if it works
> > 
> > 
> > The problem persists。
> 
> you should use these tools to compare the different browser fingerprints:
> 
> headers: [echo.free.beeceptor.com](https://echo.free.beeceptor.com/) tls: [tls.peet.ws/api/tls](https://tls.peet.ws/api/tls)
> 
> tell me what you see
![image](https://github.com/user-attachments/assets/cdd3723d-9ec3-4cf0-b410-697be0667f50)
{'method': 'GET', 'protocol': 'https', 'host': 'echo.free.beeceptor.com', 'path': '/', 'ip': '****', 'headers': {'Host': 'echo.free.beeceptor.com', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9', 'Sec-Ch-Ua': '"Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"', 'Sec-Ch-Ua-Mobile': '?0', 'Sec-Ch-Ua-Platform': '"Linux"', 'Sec-Fetch-Dest': 'document', 'Sec-Fetch-Mode': 'navigate', 'Sec-Fetch-Site': 'none', 'Sec-Fetch-User': '?1', 'Upgrade-Insecure-Requests': '1'}, 'parsedQueryParams': {}}
{'ip': '', 'http_version': '', 'method': '', 'tls': {'ciphers': ['TLS_GREASE (0x6A6A)', 'TLS_AES_128_GCM_SHA256', 'TLS_AES_256_GCM_SHA384', 'TLS_CHACHA20_POLY1305_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256', 'TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256', 'TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384', 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384', 'TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256', 'TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256', 'TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA', 'TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA', 'TLS_RSA_WITH_AES_128_GCM_SHA256', 'TLS_RSA_WITH_AES_256_GCM_SHA384', 'TLS_RSA_WITH_AES_128_CBC_SHA', 'TLS_RSA_WITH_AES_256_CBC_SHA'], 'extensions': [{'name': 'TLS_GREASE (0xeaea)'}, {'name': 'status_request (5)', 'status_request': {'certificate_status_type': 'OSCP (1)', 'responder_id_list_length': 0, 'request_extensions_length': 0}}, {'name': 'psk_key_exchange_modes (45)', 'PSK_Key_Exchange_Mode': 'PSK with (EC)DHE key establishment (psk_dhe_ke) (1)'}, {'name': 'signature_algorithms (13)', 'signature_algorithms': ['ecdsa_secp256r1_sha256', 'rsa_pss_rsae_sha256', 'rsa_pkcs1_sha256', 'ecdsa_secp384r1_sha384', 'rsa_pss_rsae_sha384', 'rsa_pkcs1_sha384', 'rsa_pss_rsae_sha512', 'rsa_pkcs1_sha512']}, {'name': 'supported_versions (43)', 'versions': ['TLS_GREASE (0x9a9a)', 'TLS 1.3', 'TLS 1.2']}, {'name': 'server_name (0)', 'server_name': 'tls.peet.ws'}, {'name': 'application_layer_protocol_negotiation (16)', 'protocols': ['h2', 'http/1.1']}, {'name': 'extensionEncryptedClientHello (boringssl) (65037)', 'data': '00000100010a0020be853b0efd082c54d848f968048074aa1169488d697b3bdcdc09cb42c05ccf5b00f0ae85df053c9b2439c36c914a376f5f1a3d0386a3d0e0daaf6f7c93477ff55839d1936fe25656d458ad6954c743d209fc527dd67a657d7778668fe292995843acbc9355720b94564313b5f283780877acb29532256a8fa6242a113dec8954e25ac5f76cb4be0e7a69a2dbc64d1258345e0642718a12f2fa8eb3cd1ab291afacae9fccff31fcfc9ef1fdb6fcbb402202f469d3528a2d60596a1eb2be8d59bb9cb142ff60183c1b60c6e8f4afc83ecfad98297271af7d8b90f70a994070420ed85599a12c4c97fc8316f8436034ee16f13ec06634d398e1593f87b29bb6d510ceae1b249393d456e4fcf3670a944d0e4fbb'}, {'name': 'extended_master_secret (23)', 'master_secret_data': '', 'extended_master_secret_data': ''}, {'name': 'session_ticket (35)', 'data': ''}, {'name': 'extensionRenegotiationInfo (boringssl) (65281)', 'data': '00'}, {'name': 'signed_certificate_timestamp (18)'}, {'name': 'ec_point_formats (11)', 'elliptic_curves_point_formats': ['0x00']}, {'name': 'application_settings (17513)', 'protocols': ['h2']}, {'name': 'compress_certificate (27)', 'algorithms': ['brotli (2)']}, {'name': 'key_share (51)', 'shared_keys': [{'TLS_GREASE (0xaaaa)': '00'}, {'X25519 (29)': '18ffe93e060c1775309f90849aae12a0798e01ff0ba9202a3bf4b9df27a8e317'}]}, {'name': 'supported_groups (10)', 'supported_groups': ['TLS_GREASE (0xaaaa)', 'X25519 (29)', 'P-256 (23)', 'P-384 (24)']}, {'name': 'TLS_GREASE (0xfafa)'}], 'tls_version_record': '771', 'tls_version_negotiated': '772', 'ja3': '771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,5-45-13-43-0-16-65037-23-35-65281-18-11-17513-27-51-10,29-23-24,0', 'ja3_hash': '97e5ced16c1bc2ca92dcc40fe8ba183d', 'ja4': 't13d1516h2_8daaf6152771_b1ff8ab2d16f', 'peetprint': 'GREASE-772-771|2-1.1|GREASE-29-23-24|1027-2052-1025-1283-2053-1281-2054-1537|1|2|GREASE-4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53|0-10-11-13-16-17513-18-23-27-35-43-45-5-51-65037-65281-GREASE-GREASE', 'peetprint_hash': '8ad9325e12f531d2983b78860de7b0ec', 'client_random': 'd17466977b52f9c9bd50ddcf9acdd1f5a5fc208a2b241b3ef6e2dde84e26a0bf', 'session_id': '867ef059d3c0a15f77e2d6f692a922b4e65a0fc3e77adead8dbc28d2864ea5d7'}, 'tcpip': {'ip': {}, 'tcp': {}}}

**Comment by ObjectAscended** [comment]
update your browser to latest version

**Comment by today2004** [comment]
> update your browser to latest version

What is the minimum version of Chrome required。
Is there any other way to communicate together？

**Comment by ObjectAscended** [comment]
update to version 127

**Comment by today2004** [comment]
update 127 There are still issues
![image](https://github.com/user-attachments/assets/9f8a4d94-e60d-4693-8a76-13509d4c9517)

**Comment by ObjectAscended** [comment]
do you have xvfb

**Comment by today2004** [comment]
> xvfb
There should be a way to check?

**Comment by ObjectAscended** [comment]
https://www.geeksforgeeks.org/how-to-install-xvfb-on-ubuntu/

**Comment by today2004** [comment]
> https://www.geeksforgeeks.org/how-to-install-xvfb-on-ubuntu/

Checked the installed ones。
![image](https://github.com/user-attachments/assets/78e81b54-5e73-4578-83f5-2392c8cb8f8b)

**Comment by ObjectAscended** [comment]
what is the site?
have you tried doing it manually to see if that works?

**Comment by today2004** [comment]
> what is the site? have you tried doing it manually to see if that works?

I'll reset the environment today and try again. Thank you。
